// Mocks generated by Mockito 5.4.4 from annotations
// in laverdi/test/src/data/auth/data_sources/local_auth_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:laverdi/src/data/services/secure_database.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SecureDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureDatabase extends _i1.Mock implements _i2.SecureDatabase {
  @override
  _i3.Future<Map<String, dynamic>> get({
    required String? boxName,
    required dynamic key,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [],
          {
            #boxName: boxName,
            #key: key,
          },
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<void> remove({
    required String? boxName,
    required dynamic key,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #remove,
          [],
          {
            #boxName: boxName,
            #key: key,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> save({
    required String? boxName,
    required dynamic key,
    required Map<String, dynamic>? value,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #save,
          [],
          {
            #boxName: boxName,
            #key: key,
            #value: value,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
