name: laverdi
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mobx: ^2.0.7+5
  flutter_mobx: ^2.0.6+1
  provider: ^6.0.3
  font_awesome_flutter: ^10.1.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  mobx_codegen: ^2.0.7

flutter:

  uses-material-design: true

  assets:
    - assets/images/laverdi_background.jpg

  fonts:
    - family: Fahkwang
      fonts:
        - asset: assets/fonts/Fahkwang-Regular.ttf
        - asset: assets/fonts/Fahkwang-Bold.ttf
          weight: 700
