name: laverdi
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">3.0.0 <4.0.0"

dependencies:
  firebase_auth: ^5.4.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  lint: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/laverdi_logo.png"
  min_sdk_android: 24

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/laverdi_background.jpg
    - assets/images/laverdi_logo.png
    - assets/images/default_recipe_pic.jpg    

  fonts:
    - family: Fahkwang
      fonts:
        - asset: assets/fonts/Fahkwang-Regular.ttf
        - asset: assets/fonts/Fahkwang-Bold.ttf
          weight: 700
